video_source_folder:
    /home/felipe/ai/toptal/benetech/VideoDeduplication/data/augmented_videos/
destination_folder:
    /home/felipe/ai/toptal/benetech/VideoDeduplication/data/
root_folder_intermediate:
    representations
video_level_folder:
    /home/felipe/ai/toptal/benetech/VideoDeduplication/data/representations/video_level
video_signatures_folder:
    /home/felipe/ai/toptal/benetech/VideoDeduplication/data/representations/video_signatures
match_distance:
    0.75
video_list_filename:
    video_dataset_list.txt
filter_dark_videos:
    true
filter_dark_videos_thr:
    2
min_video_duration_seconds:
    3
detect_scenes:
    true


