video_source_folder:
    /datadrive/test_dataset/
destination_folder:
    /datadrive/
root_folder_intermediate:
    representations
video_level_folder:
    /datadrive/intermediate/video_level
video_signatures_folder:
    /datadrive/intermediate/video_signatures
match_distance:
    0.3
video_list_filename:
    video_dataset_list.txt
    
