video_source_folder:
    /datadrive/test_dataset/
destination_folder:
    /datadrive/
root_folder_intermediate:
    representations
video_level_folder:
    /datadrive/representations/video_level
video_signatures_folder:
    /datadrive/representations/video_signatures
match_distance:
    0.75
video_list_filename:
    video_dataset_list.txt
filter_dark_videos:
    true
filter_dark_videos_thr:
    2
min_video_duration_seconds:
    3
detect_scenes:
    true

use_pretrained_model_local_path:
    true

pretrained_model_local_path:
    /home/felipe/ai/toptal/benetech/VideoDeduplication/data/vgg_16.ckpt

# DB Settings
use_db:
    true
conninfo:
    postgres://postgres:admin@localhost:5432/test
keep_fileoutput:
    true