video_source_folder:
    /datadrive/test_dataset/
destination_folder:
    datadrive/
root_folder_intermediate:
    representations
match_distance:
    0.75
video_list_filename:
    video_dataset_list.txt
filter_dark_videos:
    true
filter_dark_videos_thr:
    2
min_video_duration_seconds:
    3
detect_scenes:
    true

use_pretrained_model_local_path:
    true

pretrained_model_local_path:
    /datadrive/model/vgg_16.ckpt

# DB Settings
use_db:
    true
conninfo:
    postgres://postgres:admin@postgres:5432/videodeduplicationdb
keep_fileoutput:
    true
