version: '2.3'

services:
  postgres:
    image: postgres
    environment:
      # Remember to change the config.yaml [conninfo] file if you change this 
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "videodeduplicationdb"
      WINNOW_CONFIG: /config.yml
    ports:
      - "5432:5432"
    volumes:
      # Replace by the path on your host machine where you would like to save your DB data
      - ~/datadrive/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  dedup-app:
    # This can be replaced by the online repository reference if you haven't built a local docker image
    image: wingpu 
    runtime: nvidia
    command: bash -ic "bash serve_jupyter.sh"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      # Replace by the path on your host machine where you placed the source data
        - /datadrive:/project/data
    ports:
      - "16543:80"
      - "8888:8888"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
