name: winnow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - scikit-learn==0.23.2
  - scipy
  - tensorflow-gpu==1.15
  - tqdm
  - sqlalchemy
  - psycopg2
  - pytest
  - jupyter
  - jupyterlab
  - pysoundfile
  - h5py==2.9.0
  - ffmpeg
  - numba
  - pynndescent
  - luigi
  - tabulate
  - umap-learn
  - networkit
  - pip
  - pip:
      - lmdb
      - image
      - imageio
      - moviepy
      - opencv-contrib-python
      - pillow
      - scenedetect
      - pyyaml
      - cached-property
      - dataclasses
      - celery==5.0.5
      - redis
      - billiard
      - librosa
      - fire
      - inquirer
      - pytimeparse
      - annoy
      - yt-dlp
      - dacite
      - deprecation
      - trimap
      - pacmap
      - torch
      - typing_extensions==4.1.1
      - grpcio==1.43.0
      - grpcio-tools==1.43.0

