name: winnow
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cuml
  - numpy==1.22.3
  - matplotlib==3.5.1
  - pandas==1.2.4  
  - scikit-learn==1.0.2
  - scipy==1.8.0
  - tqdm
  - sqlalchemy
  - psycopg2
  - pytest
  - jupyter
  - jupyterlab
  - pysoundfile
  - h5py==3.6.0
  - ffmpeg==5.0.0
  - numba
  - pynndescent
  - luigi
  - tabulate
  - umap-learn
  - networkit
  - pip==22.0.4
  - pip:
      - lmdb
      - image
      - imageio
      - moviepy
      - opencv-contrib-python
      - pillow
      - scenedetect
      - pyyaml==6.0
      - cached-property
      - dataclasses
      - celery
      - redis
      - billiard
      - librosa
      - fire
      - inquirer
      - pytimeparse
      - annoy
      - yt-dlp
      - dacite
      - deprecation
      - grpcio==1.44.0
      - grpcio-tools==1.44.0
      - tensorflow==2.8.0
      - trimap
      - pacmap
<<<<<<< HEAD
      - torch
      - typing_extensions==4.1.1
      - grpcio==1.43.0
      - grpcio-tools==1.43.0
=======
      - tf-slim
>>>>>>> final environment changes

