name: Winnow CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development]

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          pip install -r requirements-winnow-unit-tests.txt
      - name: Check formatting with black
        run: |
          # Check formatting of scripts at the root folder
          black --line-length 120 --check *.py
          # Check formatting of the db package
          black --line-length 120 --check db
          # Check formatting of the winnow package
          black --line-length 120 --check winnow
          # Check formatting of the winnow tests
          black --line-length 120 --check tests
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 winnow --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # --ignore=E203 as it is not PEP8 and black style compliant. See: https://github.com/psf/black/issues/315
          flake8 winnow --count --exit-zero --max-complexity=10 --ignore=E203 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export PYTHONPATH="$(pwd)"
          pytest tests/winnow